version: "3"
services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
